### ISSUE TITLE
active line highlight

### ISSUE THREAD

**Issue by DanielPintilei** [anthonyrom/true-ocean#1]
when "highlight active line" option is on,  the text is not distinguishable from the background color of the highlighted line
and same for the tags that are placed inside the selected line but are not directly selected
i think the background color for the highlight should be dark

**Comment by anthonyrom** [comment]
Great find. I don't use the highlight active line feature, so I never would have spotted this. Thanks! An update will come soon to fix this.

**Comment by anthonyrom** [comment]
Support is now added - tell me what you think of my implementation!

**Comment by DanielPintilei** [comment]
red underline is nice (for some reason unknown to me, on tags like google fonts link for example, the underline doesn't start from the beginning of the tag) but to see a better approach to this check Brackets' default dark theme — the background color of the active line has a lower opacity than the background color of the selected tag

**Comment by anthonyrom** [comment]
That thing with the underline not starting in the right place must be a Brackets bug - this theme's code doesn't affect that at all. 

The way the default Brackets Dark theme deals with this is that the selected tag is highlighted in a different color. As you said, with this theme, the selected tags are underlined in red instead. This is still visible with Highlight Active Line enabled. I considered both options when making the theme, and ultimately chose the red underline. Thank you for the suggestion, but unless there are more requests to change this, I will keep it as the red underline.

**Comment by DanielPintilei** [comment]
in my opinion, different highlight for line and tags is useful, especially when you have tags inside tags
thanks

**Comment by anthonyrom** [comment]
You make a good point there. I will look into it and see what I can do.

Thanks.
